### ISSUE TITLE
Please publish this!

### ISSUE THREAD

**Issue by guthriec** [mongodb/mongodb-vapor#10]
I'm fairly new to Swift Package Manager, so please excuse me if I'm misunderstanding something. I'm getting "Failed to resolve dependencies" on this package, which I think is working as intended (you haven't yet tagged any commits). I'll happily copy over your code, but it's a bit of a pain. A public beta version of the package would be amazing.

**Comment by 0xTim** [comment]
@guthriec how are you including it?

**Comment by guthriec** [comment]
```
// swift-tools-version:5.2
import PackageDescription

let package = Package(
    name: "MyProjectServer",
    platforms: [
       .macOS(.v10_15)
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "4.7.0"),
        .package(url: "https://github.com/mongodb/mongodb-vapor.git", from: "1.0.0")
    ],
    targets: [
        .target(
            name: "App",
            dependencies: [
                .product(name: "Vapor", package: "vapor"),
                .product(name: "MongoDBVapor", package: "mongodb-vapor"),
            ],
            swiftSettings: [
                // Enable better optimizations when building in Release configuration. Despite the use of
                // the `.unsafeFlags` construct required by SwiftPM, this flag is recommended for Release
                // builds. See <https://github.com/swift-server/guides/blob/main/docs/building.md#building-for-production> for details.
                .unsafeFlags(["-cross-module-optimization"], .when(configuration: .release))
            ]
        ),
        .target(name: "Run", dependencies: [
            .target(name: "App"),
            .product(name: "MongoDBVapor", package: "mongodb-vapor"),
        ]),
        .testTarget(name: "AppTests", dependencies: [
            .target(name: "App"),
            .product(name: "XCTVapor", package: "vapor"),
        ])
    ]
)
```

**Comment by 0xTim** [comment]
Cool since there's no tag, you can just depend on the branch directly:
```swift
.package(url: "https://github.com/mongodb/mongodb-vapor.git", .branch("main"))
```
Note that you might encounter breaking changes when updating which is why it hasn't been tagged yet

**Comment by kmahar** [comment]
@guthriec Thank you for reaching out and I'm happy to hear you are excited to try the library! I'm planning to tag a beta release very soon (within the next week or so) - as @0xTim notes you can depend on the main branch in the meantime 🙂

Please let us know if you run into any issues or have any suggestions for improvement as you try it out!

**Comment by guthriec** [comment]
Awesome, that worked! Like I said, I'm still very new to SPM. Maybe it's worth updating the docs?

Anyway I'm glad to see that this is being maintained so actively. I'll be sure to file any more issues I run into.

**Comment by kmahar** [comment]
In #11 I ended up adding support for keeping the version string in the README auto-updated with each release. I also just tagged a beta release so you can now depend on that tag if you'd like to: https://github.com/mongodb/mongodb-vapor/releases/tag/v1.0.0-beta.0

Since it's a beta you might want to depend on the version exactly, just in case any breaking changes are made (while we don't currently plan on any, it is possible if we receive feedback about any issues with the API):
```
.package(url: "https://github.com/mongodb/mongodb-vapor", .exact("1.0.0-beta.0"))
```
