### ISSUE TITLE
Docker build requirement

### ISSUE THREAD

**Issue by dotmain** [mongodb/mongodb-vapor#14]
Hello Mrs Maher, 

As building docker image with vapor and mongo, The docker image that vapor provides requires an added RUN command to work as expected, or the docker build fails on Ubuntu 20.04

RUN apt-get update && apt-get install -y libssl-dev

Thought i'd share the insight, if a not yet known issue. 

//.main

**Comment by kmahar** [comment]
@dotmain Thanks for reaching out! I'm going to call this out in the README for now. We have a [ticket](https://jira.mongodb.org/browse/SWIFT-1218) tracking work to add Docker integration to the [Vapor template](https://github.com/mongodb/mongodb-vapor-template) we provide as well, I've made a note on there that we should handle this in that integration.

**Comment by dotmain** [comment]
You're welcome. Happy to help. 
Since having a ticket for it, here is a working docker image with composer with vapor cli integration. 
: )

```vapor new MyProject --template https://github.com/dotmain/native-mongo-vapor-template``` 
```cd MyProject```

available scripts:
```make build```
```make run```
```make down```
```make clean```


https://github.com/dotmain/native-mongo-vapor-template

**Comment by kmahar** [comment]
@dotmain Thank you!!

**Comment by kmahar** [comment]
I am going to close this issue as I updated the README with relevant info in #15. Thanks again for reaching out!
